### ISSUE TITLE
LocationView Issue  (GLSurfaceView)

### ISSUE THREAD

**Issue by karim-mamdouh** [Navigine/Indoor-Navigation-Android-Mobile-SDK-2.0#11]
When I add a LocationView in my xml I get the following error: 

2021-12-31 09:34:01.454 28778-28866/com.example.navisafeapp E/ple.navisafeap: No implementation found for void com.navigine.view.internal.GLRendererWrapper.nativeSetNavigineSdk() (tried Java_com_navigine_view_internal_GLRendererWrapper_nativeSetNavigineSdk and Java_com_navigine_view_internal_GLRendererWrapper_nativeSetNavigineSdk__)
2021-12-31 09:34:01.456 28778-28866/com.example.navisafeapp E/AndroidRuntime: FATAL EXCEPTION: GLThread 1860
    Process: com.example.navisafeapp, PID: 28778
    java.lang.UnsatisfiedLinkError: No implementation found for void com.navigine.view.internal.GLRendererWrapper.nativeSetNavigineSdk() (tried Java_com_navigine_view_internal_GLRendererWrapper_nativeSetNavigineSdk and Java_com_navigine_view_internal_GLRendererWrapper_nativeSetNavigineSdk__)
        at com.navigine.view.internal.GLRendererWrapper.nativeSetNavigineSdk(Native Method)
        at com.navigine.view.internal.GLRendererWrapper.setNavigineSdk(GLRendererWrapper.java:130)
        at com.navigine.view.LocationView$1.run(LocationView.java:64)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1502)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

It also seems that the location is not being downloaded, not sure if the error is related (the location id from location manager is 0, and when I set it to the one shown in the CMS, it gives an error downloading).

**Comment by PavelTychinin** [comment]
Hi, thanks for your reply.
Is it NavigineDemo application or your own?

It looks like the native part was not loaded.

Make sure that you have called function `Navigine.initialize(Context);` before using all other methods of NavigineSDK.

If nothing happens it would be great if you specify your device, android version (real device or emulator) and library version
